version: '3.5'

services:

  gps-ferrari-cli:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - ./ferrari:/var/www
      - composer:/root/.composer/cache

  gps-lamborghini-cli:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - ./lamborghini:/var/www
      - composer:/root/.composer/cache

  gps-sdk:
    image: google/cloud-sdk

volumes:
  composer: